sudo: required

services: 
  - docker

before_install:
  - docker compose build

script:
  - docker run adrastopoulos/economica yarn lint

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push adrastopoulos/economica:bot
  - docker push adrastopoulos/economica:dash
  - docker push adrastopoulos/economica:proxy