version: '1.0.0'

services:
  economica:
    build: .
    container_name: Economica
    restart: always
    env_file: .env
    ports: 
      - "3000"
    depends_on:
      - economica-postgres
    networks: 
      - default
  economica-postgres:
    image: postgres:latest
    container_name: Economica-DB
    expose:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    networks: 
      - default

      