version: "3.9"

services:
  dashboard:
    container_name: dashboard
    image: adrastopoulos/economica:dash
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - default
    env_file:
      - ./apps/dashboard/.env
  bot:
    container_name: bot
    image: adrastopoulos/economica:bot
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
    restart: always
    networks:
      - default
    env_file:
      - ./apps/bot/.env
  nginx:
    container_name: proxy
    ports:
      - 80:80
    depends_on:
      - dashboard
      - bot
    networks:
      - default
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - 'host.docker.internal:host-gateway'
