version: 3.9

services:
  dashboard:
    x-aws-pull_credentials: arn:aws:secretsmanager:us-east-1:787454512443:secret:aws-7Z7iwX
    container_name: dashboard
    image: adrastopoulos/economica:dash
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    restart: always
    env_file:
      - .env.production
    ports:
      - 3000:3000
    networks:
      - default
  bot:
    x-aws-pull_credentials: arn:aws:secretsmanager:us-east-1:787454512443:secret:aws-7Z7iwX
    container_name: bot
    image: adrastopoulos/economica:bot
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
    restart: always
    env_file:
      - .env.production
  nginx:
    container_name: proxy
    ports:
      - 80:80
    depends_on:
      - dashboard
      - bot
    networks:
      - default
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - 'host.docker.internal:host-gateway'
