services:
  bot:
    build: .
    container_name: bot
    restart: always
    env_file: 
      - ../../.env
    ports: 
      - "3000"
    depends_on:
      - postgres
    networks: 
      - default
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    networks: 
      - default

      