name: Docker Image CI

on:
  push:
    branches: [ "Production" ]
  pull_request:
    branches: [ "Production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        touch apps/dashboard/.env.local
        echo DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} >> apps/dashboard/.env.local 
        docker compose -f docker-compose.yml build --no-cache --pull
