name: Docker Image CI

on:
  push:
    branches: [ "Production" ]
  pull_request:
    branches: [ "Production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose -f docker-compose.yml build --no-cache --pull
